server:
  port: 8082
spring:
  redis:
    port: 6379
    host: 127.0.0.1
  session:
    store-type: redis
  thymeleaf:
    cache: false
  application:
    name: gulimall-member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.210.58:3306/gulimall_ums?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 121.40.210.58:8848
mybatis-plus:
  type-aliases-package: com.atguigu.gulimall.member.entity
  mapper-locations: classpath:/mapper/member/*Dao.xml
  global-config:
    db-config:
      id-type: auto