server:
  port: 9000
spring:
  application:
    name: gulimall-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.60.176:3306/gulimall_oms?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  type-aliases-package: com.atguigu.gulimall.order.entity
  mapper-locations: classpath:/mapper/order/*Dao.xml
  global-config:
    db-config:
      id-type: auto