server:
  port: 9000
spring:
  rabbitmq:
    virtual-host: /
    host: 121.40.210.58
    port: 5672
    #    开启发送端消息抵达broker确认
    publisher-confirms: true
    #    开启发送端消息抵达队列确认
    publisher-returns: true
    #    只要抵达队列，以异步方式优先回调returnconfirm
    template:
      mandatory: true
  application:
    name: gulimall-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.60.176:3306/gulimall_oms?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 121.40.210.58:8848

mybatis-plus:
  type-aliases-package: com.atguigu.gulimall.order.entity
  mapper-locations: classpath:/mapper/order/*Dao.xml
  global-config:
    db-config:
      id-type: auto