server:
  port: 9000
spring:
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    virtual-host: /
    host: 121.40.210.58
    port: 5672
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  application:
    name: gulimall-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gulimall_oms?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 121.40.210.58:8848
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
mybatis-plus:
  type-aliases-package: com.atguigu.gulimall.order.entity
  mapper-locations: classpath:/mapper/order/*Dao.xml
  global-config:
    db-config:
      id-type: auto
feign:
  client:
    config:
      gulimall-member:
        connectTimeout: 10000
        readTimeout: 10000
      gulimall-cart:
        connectTimeout: 10000
        readTimeout: 10000
alipay:
  app_id: 2021000119606313
  notify_url: http://xb6cg22x28.52http.net/order/pay/alipay/success
  return_url: http://localhost:2000/pay/success.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do