spring:
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 121.40.210.58:8848
  thymeleaf:
    cache: false