#server:
#  port: 88
#spring:
#  application:
#    name: gulimall-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        namespace: e545c141-f794-4b40-ad0e-bebff183e997
