spring:
  application:
    name: gulimall-auths-server
  session:
    store-type: redis
  cloud:
    nacos:
      discovery:
        server-addr: 121.40.210.58:8848
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
server:
  port: 20000
  servlet:
    session:
      timeout: 30m
feign:
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
