server:
  port: 30000
spring:
  cloud:
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-third-party