server:
  port: 30000
spring:
  cloud:
    alicloud:
      access-key: LTAI5t5iT3UQHXopsmfHSM22
      secret-key: w4gZOVoY6k5kFj6PSSGzfe8PsLelzT
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-third-party